name: config_runtime
description: Unified config discovery/merge/validation runtime for all engines.
version: 0.1.0
environment: { sdk: '>=3.3.0 <4.0.0' }
dependencies:
     yaml: ^3.1.2
     path: ^1.9.0
     collection: ^1.18.0
     csv: ^6.0.0
     json_schema2: ^5.1.3
     meta: ^1.12.0
dev_dependencies:
     lints: ^3.0.0
     test: ^1.25.0
flutter:
     assets: [assets/schemas/]
