name: schema_validator
description: CLI tool to validate content pack JSON/YAML files against schemas.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  json_schema2: ^2.0.1

dev_dependencies:
  test: ^1.25.0
