name: schema_validator_tool
description: CLI to validate packs/configs and emit artifacts for CI.
version: 0.1.0
publish_to: none

environment:
     sdk: '>=3.3.0 <4.0.0'

dependencies:
     config_runtime:
          path: ../../packages/config_runtime
     args: ^2.5.0
     yaml: ^3.1.2
     json_schema2: ^5.1.3

dev_dependencies:
     test: ^1.25.0

executables:
     validate_configs: validate_configs
