analyzer:
     exclude:
          - bricks/**/__brick__/**
          - bricks/**/__bricks__/**
          - bricks/__brick__/**
          - bricks/__bricks__/**
     errors:
          unused_import: error
          unnecessary_import: error
          dead_code: error
          unnecessary_null_checks: error

linter:
     rules:
          - avoid_print
          - prefer_const_constructors
          - prefer_final_locals
          - unnecessary_this
          - sort_child_properties_last
