name: flutter_game_ecosystem

packages:
     - packages/* # ui_shell, providers, services, etc.
     - packages/*/* # services subpackages (analytics_firebase_adapter, core_services, core_services_isar)
     - modules/genres/* # game_scenes, etc.
     - examples/* # demo_game
     # game_core relocated under packages/

ignore:
     - '**/build/**'
     - '**/.dart_tool/**'

ide:
     intellij:
          enabled: false
     vscode:
          enabled: true

scripts:
     bootstrap: melos bootstrap
     clean: melos exec -- flutter clean
     get: melos exec -- flutter pub get
     analyze: melos exec -- dart analyze .
     format: melos exec -- dart format .
     flutter:warm: flutter --version
     test: melos run flutter:warm && melos exec --concurrency=1 -- flutter test --reporter expanded
     example: melos exec --scope="demo_game" -- flutter run
     check: >
          melos run format &&
          melos run analyze &&
          melos run test
