name: services
description: Core service ports (economy, save/profile, telemetry) with no platform impls.
version: 0.1.0
publish_to: 'none'

environment:
     sdk: '>=3.3.0 <4.0.0'

dependencies:
     flutter:
          sdk: flutter
     amplitude_flutter: ^4.3.7
     firebase_analytics: ^12.0.1
     # Using local stub of in_app_purchase for testing / CI without store SDKs.
     in_app_purchase:
          path: ../in_app_purchase

dev_dependencies:
     flutter_test:
          sdk: flutter
     lints: ^5.0.0
