name: game_core
description: Flame/Forge2D extensions, base scene lifecycle, event bus, contracts.
version: 0.1.0
publish_to: 'none'

environment:
     sdk: '>=3.3.0 <4.0.0'

dependencies:
     flutter:
          sdk: flutter
     flame: ^1.17.0
     flame_forge2d: ^0.18.1

dev_dependencies:
     flutter_test:
          sdk: flutter
     lints: ^5.0.0
