meta:
  version: 1
  authors: ["shannon","arena_team"]
  created: "2025-09-10"

include:
  - board.yaml
  - loot.index.yaml

analytics:
  on_swap: match.swap
  on_match: match.match
  on_cascade_end: match.cascade_end
  on_board_stable: match.board_stable
