name: demo_game
description: Demo app wiring game_ui + category registry.
publish_to: 'none'
version: 0.1.0
environment:
     sdk: '>=3.3.0 <4.0.0'
dependencies:
     flutter:
          sdk: flutter
     flutter_riverpod: ^2.5.1
     # local unawaited helper used; avoid adding a runtime helper dependency here.
     shared_utils:
          path: ../../packages/shared_utils
     go_router: ^14.2.0
     ui_shell:
          path: ../../packages/ui_shell
     services:
          path: ../../packages/services
     providers:
          path: ../../packages/providers
     core_services:
          path: ../../packages/services/core_services
     game_scenes:
          path: ../../modules/genres/game_scenes
     game_core:
          path: ../../packages/game_core
     match:
          path: ../../modules/genres/match
     survivor:
          path: ../../modules/genres/survivor
     idle:
          path: ../../modules/genres/idle
dev_dependencies:
     flutter_test:
          sdk: flutter
     flutter_lints: ^4.0.0
flutter:
     uses-material-design: true
