name: ui_shell
description: Unified shell widgets (nav, theming, store entry, account) for the game ecosystem.
version: 0.1.0
publish_to: 'none'

environment:
     sdk: '>=3.3.0 <4.0.0'

dependencies:
     flutter:
          sdk: flutter
     hooks_riverpod: ^2.5.1
     flutter_hooks: ^0.20.5

dev_dependencies:
     flutter_test:
          sdk: flutter
     lints: ^5.0.0

flutter:
     uses-material-design: true
