name: rpg
description: Basic RPG stats and utilities.
version: 0.1.0
environment:
     sdk: '>=3.3.0 <4.0.0'
dependencies:
     flutter:
          sdk: flutter
dev_dependencies:
     flutter_test:
          sdk: flutter
     flutter_lints: ^4.0.0
