name: Accept Goldens

on:
     workflow_dispatch:
          inputs:
               branch:
                    description: 'Branch to update goldens from (must be pushable)'
                    required: true
                    default: chore/update-docs-and-tech-data

jobs:
     accept:
          runs-on: ubuntu-latest
          steps:
               - name: Checkout
                 uses: actions/checkout@v4
               - name: Read Flutter pin
                 id: flutter_pin
                 run: |
                      if [ -f .github/flutter_version.txt ]; then echo "FLUTTER_VERSION=$(cat .github/flutter_version.txt)" >> $GITHUB_OUTPUT; else echo "FLUTTER_VERSION=stable" >> $GITHUB_OUTPUT; fi
               - name: Set up Flutter
                 uses: subosito/flutter-action@v2
                 with:
                      flutter-version: ${{ steps.flutter_pin.outputs.FLUTTER_VERSION }}
               - name: Pull branch
                 run: |
                      git fetch origin ${{ github.event.inputs.branch }}
                      git checkout ${{ github.event.inputs.branch }}
               - name: Copy updated goldens into main branch
                 run: |
                      # This action expects the caller to have pushed working goldens to the branch
                      echo "Manual: please merge or cherry-pick the golden updates from the branch into main" || true
