name: Auto Label Issues & PRs
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, synchronize]
permissions:
  issues: write
  pull-requests: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue || context.payload.pull_request;
            if (!issue) { return; }
            const title = issue.title.toLowerCase();
            const labels = new Set();
            if (title.startsWith("[bug]")) labels.add("bug");
            if (title.startsWith("[store]")) { labels.add("store"); labels.add("release-train"); }
            if (/(icon|screenshot|feature graphic)/i.test(issue.title)) labels.add("assets");
            if (/privacy|data safety|att|content rating/i.test(issue.title)) labels.add("compliance");
            if (/admob|rewarded|interstitial|iap|billing|monetization/i.test(issue.title)) labels.add("monetization");
            if (/analytics|remote config|event/i.test(issue.title)) labels.add("analytics");
            if (context.payload.pull_request) {
              // Label PRs by touched files after checkout
              core.info("PR detected; adding 'task' by default");
              labels.add("task");
            }
            if (labels.size === 0) return;
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: Array.from(labels)
            });
