name: Auto Label Issues
on:
  issues:
    types: [opened, edited]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels based on title
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.issue.title;
            const labels = [];
            if (title.startsWith("[Bug]")) labels.push("bug");
            if (title.startsWith("[Store]")) labels.push("store","release-train");
            if (title.startsWith("[Task]")) labels.push("task");
            if (labels.length > 0) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels
              });
            }
