name: Checklist Visibility

on:
     push:
          branches: [main]
          paths-ignore:
               - 'docs/VISIBILITY.md'
               - 'docs/metrics/task_checklist.json'
               - 'README.md'
     workflow_dispatch: {}

permissions:
     contents: write

jobs:
     generate-visibility:
          name: Generate task checklist visibility and commit
          runs-on: ubuntu-latest
          steps:
               - name: Checkout
                 uses: actions/checkout@v4
                 with:
                      fetch-depth: 0

               - name: Set up Flutter
                 uses: subosito/flutter-action@v2
                 with:
                      channel: stable
                      cache: true

               - name: Dart Pub cache path
                 run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

               - name: Activate Melos
                 run: dart pub global activate melos

               - name: Bootstrap workspace
                 run: melos bootstrap

               - name: Run checklist generator
                 run: dart run tools/generate_task_checklist.dart

               - name: Stamp doc dates
                 run: dart run tools/stamp_doc_dates.dart

               - name: Commit README/docs updates
                 run: |
                      set -e
                      CHANGED=$(git status --porcelain docs/VISIBILITY.md docs/metrics/task_checklist.json README.md | wc -l)
                      if [ "$CHANGED" -gt 0 ]; then
                        git config user.name 'ci-bot'
                        git config user.email 'ci-bot@users.noreply.github.com'
                        git add docs/VISIBILITY.md docs/metrics/task_checklist.json README.md
                        git commit -m 'chore(visibility): update task checklist visibility'
                        git push || true
                      else
                        echo "No visibility changes to commit"
                      fi
