name: CI

on:
     push:
          branches: [main, develop, 'refactor/**', 'feat/**', 'chore/**']
     pull_request:
          branches: ['**']

jobs:
     build-analyze-test-validate:
          name: Flutter + Melos + Schema Validator
          runs-on: ubuntu-latest
          env:
               ANALYTICS_MIN_TESTS: '1'
               ALLOW_COVERAGE_MISSING: '0'
               FAIL_ON_PACKAGE_STATUS: '0'
          steps:
               - name: Checkout
                 uses: actions/checkout@v4

               - name: Read Flutter pin
                 id: flutter_pin
                 run: |
                      if [ -f .github/flutter_version.txt ]; then echo "FLUTTER_VERSION=$(cat .github/flutter_version.txt)" >> $GITHUB_OUTPUT; else echo "FLUTTER_VERSION=stable" >> $GITHUB_OUTPUT; fi

               - name: Set up Flutter
                 uses: subosito/flutter-action@v2
                 with:
                      flutter-version: ${{ steps.flutter_pin.outputs.FLUTTER_VERSION }}
                      cache: true

               - name: Dart Pub cache path
                 run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

               - name: Activate Melos
                 run: dart pub global activate melos

               - name: Bootstrap workspace
                 run: melos bootstrap

               - name: Check per-package analysis includes
                 run: |
                      # Ensure per-package analysis_options.yaml reference the repo root
                      dart run tools/check_package_analysis_includes.dart

               - name: Format check
                 run: melos run format:check

               - name: Analyze
                 run: melos run analyze

               - name: Run non-golden tests
                 run: melos run test:non-goldens

               - name: Run CI-mode golden tests (temporarily disabled)
                 run: |
                      echo "CI-mode golden tests temporarily disabled due to CI-only pixel diffs. See docs/AI_TASK_LIBRARY.md for follow-up."

               - name: Collect coverage (per-package, aggregate)
                 id: collect_coverage
                 run: |
                      set -e
                      # Run `flutter test --coverage` only in packages that have a test/ dir.
                      # Exclude the demo_game goldens package to avoid golden-related failures during coverage.
                      melos exec --ignore="examples/demo_game" --concurrency=1 -- bash -lc "if [ -d test ]; then echo 'Running coverage in:' \"$(pwd)\"; flutter test --coverage || true; else echo 'No tests in:' \"$(pwd)\"; fi"
                      # Only merge coverage if any per-package coverage files were produced.
                      FOUND=0
                      for f in $(find . -name lcov.info -path "*/coverage/lcov.info" 2>/dev/null); do
                        FOUND=1
                        echo "Found coverage file: $f"
                      done
                      if [ "$FOUND" -eq 1 ]; then
                        dart run tools/merge_coverage.dart || true
                        echo "COVERAGE_MERGED=1" >> $GITHUB_OUTPUT
                      else
                        echo "No coverage files found, skipping merge." >&2
                        echo "COVERAGE_MERGED=0" >> $GITHUB_OUTPUT
                      fi

               - name: Upload merged coverage artifact
                 if: steps.collect_coverage.outputs.COVERAGE_MERGED == '1'
                 uses: actions/upload-artifact@v4
                 with:
                      name: merged-coverage-lcov
                      path: coverage/lcov.info

               - name: Quality gates consolidated
                 id: gates
                 run: |
                      set -e
                      dart run tools/run_quality_gates.dart | tee quality_gates.log
                      HASH=$(dart run tools/print_parity_spec_hash.dart)
                      echo "STUB_PARITY_SPEC_HASH=$HASH" >> $GITHUB_ENV
                      echo "STUB_PARITY_OK=1" >> $GITHUB_ENV
               - name: Upload quality gate summary
                 uses: actions/upload-artifact@v4
                 with:
                      name: quality-gates-log
                      path: quality_gates.log

               - name: Update metrics doc
                 run: dart run tools/update_metrics.dart

               - name: Commit metrics update
                 if: github.event_name == 'push'
                 run: |
                      if [[ -n $(git status --porcelain docs/METRICS.md) ]]; then
                        git config user.name 'ci-bot'
                        git config user.email 'ci-bot@users.noreply.github.com'
                        git add docs/METRICS.md
                        git commit -m 'chore(metrics): update metrics after CI'
                        git push || true
                      fi

               - name: Validate content pack schemas
                 run: dart run tools/schema_validator/bin/validate_schemas.dart
