name: CI (Flutter/Melos)
on:
     pull_request:
     push:
          branches: [main]
permissions:
     contents: read
jobs:
     build:
          runs-on: ubuntu-latest
          steps:
               - uses: actions/checkout@v4
               - uses: subosito/flutter-action@v2
                 with:
                      channel: 'stable'
               - name: Install Java
                 uses: actions/setup-java@v4
                 with:
                      distribution: 'temurin'
                      java-version: '17'
               - name: Install tools
                 run: |
                      flutter --version
                      dart --version
                      dart pub global activate melos
                      echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
               - name: Bootstrap
                 run: melos bootstrap
               - name: Format check
                 run: dart format --output=none --set-exit-if-changed .
               - name: Analyze
                 run: flutter analyze
               - name: Tests
                 run: flutter test --coverage
               - name: Upload coverage (optional)
                 if: env.CODECOV_TOKEN != ''
                 env:
                      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
                 uses: codecov/codecov-action@v4
                 with:
                      token: ${{ env.CODECOV_TOKEN }}
                      files: coverage/lcov.info
