name: CI

on:
     push:
          branches: [main, develop, 'refactor/**', 'feat/**', 'chore/**']
     pull_request:
          branches: ['**']

jobs:
     build-analyze-test-validate:
          name: Flutter + Melos + Schema Validator
          runs-on: ubuntu-latest

          steps:
               - name: Checkout
                 uses: actions/checkout@v4

               # Flutter includes Dart; we’ll use it for melos & the validator.
               - name: Set up Flutter
                 uses: subosito/flutter-action@v2
                 with:
                      channel: stable
                      cache: true

               - name: Dart Pub cache path
                 run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

               - name: Activate Melos
                 run: dart pub global activate melos

               - name: Bootstrap workspace
                 run: melos bootstrap

               # Optional: enforce formatting; fail if changes are needed.
               - name: Format check
                 run: melos run format -- --set-exit-if-changed

               - name: Analyze
                 run: melos run analyze

               - name: Test
                 run: melos run test

               # Schema validation (uses defaults set in the CLI: templates/schemas + winter_2025)
               - name: Validate content pack schemas
                 run: dart run tools/schema_validator/bin/validate_schemas.dart
