name: CI

on:
     push:
          branches: [main, develop, 'refactor/**', 'feat/**', 'chore/**']
     pull_request:
          branches: ['**']

jobs:
     build-analyze-test-validate:
          name: Flutter + Melos + Schema Validator
          runs-on: ubuntu-latest
          env:
               ANALYTICS_MIN_TESTS: '1'
               ALLOW_COVERAGE_MISSING: '0'
               FAIL_ON_PACKAGE_STATUS: '0'
          steps:
               - name: Checkout
                 uses: actions/checkout@v4

               - name: Set up Flutter
                 uses: subosito/flutter-action@v2
                 with:
                      channel: stable
                      cache: true

               - name: Dart Pub cache path
                 run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

               - name: Activate Melos
                 run: dart pub global activate melos

               - name: Bootstrap workspace
                 run: melos bootstrap

               - name: Format check
                 run: melos run format:check

               - name: Analyze
                 run: melos run analyze

               - name: Test
                 run: melos run test

               - name: Collect coverage (aggregate)
                 run: |
                      flutter test --coverage
                      # Merge per-package coverage files if present
                      dart run tools/merge_coverage.dart || true

               - name: Quality gates consolidated
                 id: gates
                 run: |
                      set -e
                      dart run tools/run_quality_gates.dart | tee quality_gates.log
                      HASH=$(dart run tools/print_parity_spec_hash.dart)
                      echo "STUB_PARITY_SPEC_HASH=$HASH" >> $GITHUB_ENV
                      echo "STUB_PARITY_OK=1" >> $GITHUB_ENV
               - name: Upload quality gate summary
                 uses: actions/upload-artifact@v4
                 with:
                      name: quality-gates-log
                      path: quality_gates.log

               - name: Update metrics doc
                 run: dart run tools/update_metrics.dart

               - name: Commit metrics update
                 if: github.event_name == 'push'
                 run: |
                      if [[ -n $(git status --porcelain docs/METRICS.md) ]]; then
                        git config user.name 'ci-bot'
                        git config user.email 'ci-bot@users.noreply.github.com'
                        git add docs/METRICS.md
                        git commit -m 'chore(metrics): update metrics after CI'
                        git push || true
                      fi

               - name: Validate content pack schemas
                 run: dart run tools/schema_validator/bin/validate_schemas.dart
