name: Consolidate Stack Docs

on:
     push:
          branches: [main]
          paths-ignore:
               - 'docs/STACK.md'
               - 'docs/metrics/stack_index.json'
               - 'README.md'
     workflow_dispatch: {}

permissions:
     contents: write

jobs:
     consolidate:
          runs-on: ubuntu-latest
          steps:
               - name: Checkout
                 uses: actions/checkout@v4
                 with:
                      fetch-depth: 0

               - name: Set up Flutter
                 uses: subosito/flutter-action@v2
                 with:
                      channel: stable
                      cache: true

               - name: Dart Pub cache path
                 run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

               - name: Activate Melos
                 run: dart pub global activate melos

               - name: Bootstrap workspace
                 run: melos bootstrap

               - name: Consolidate stack docs
                 run: dart run tools/consolidate_stack_docs.dart

               - name: Commit consolidated stack
                 run: |
                      set -e
                      CHANGED=$(git status --porcelain docs/STACK.md docs/metrics/stack_index.json README.md | wc -l)
                      if [ "$CHANGED" -gt 0 ]; then
                        git config user.name 'ci-bot'
                        git config user.email 'ci-bot@users.noreply.github.com'
                        git add docs/STACK.md docs/metrics/stack_index.json README.md
                        git commit -m 'chore(docs): consolidate stack docs'
                        git push || true
                      else
                        echo "No stack doc changes to commit"
                      fi
