name: Coverage Ratchet

on:
     schedule:
          - cron: '0 6 * * *'
     workflow_dispatch: {}

permissions:
     contents: write

jobs:
     ratchet:
          runs-on: ubuntu-latest
          steps:
               - uses: actions/checkout@v4
                 with:
                      fetch-depth: 0
               - name: Read Flutter pin
                 id: flutter_pin
                 run: |
                      if [ -f .github/flutter_version.txt ]; then echo "FLUTTER_VERSION=$(cat .github/flutter_version.txt)" >> $GITHUB_OUTPUT; else echo "FLUTTER_VERSION=stable" >> $GITHUB_OUTPUT; fi
               - uses: subosito/flutter-action@v2
                 with:
                      flutter-version: ${{ steps.flutter_pin.outputs.FLUTTER_VERSION }}
                      cache: true
               - name: Install dependencies
                 run: flutter pub get
               - name: Run tests to produce coverage
                 run: bash tools/run_all_tests.sh
               - name: Run coverage ratchet
                 run: dart run tools/coverage_ratchet.dart
               - name: Commit policy bump
                 run: |
                      set -e
                      if ! git diff --quiet -- tools/coverage_policy.yaml; then
                        git config user.name 'ci-bot'
                        git config user.email 'ci-bot@users.noreply.github.com'
                        git add tools/coverage_policy.yaml
                        git commit -m 'chore(metrics): bump coverage policy floor [skip ci]'
                        git push || true
                      else
                        echo 'No ratchet needed.'
                      fi
