name: Golden Image Guard
on:
     pull_request:
permissions:
     contents: read
jobs:
     goldens:
          runs-on: ubuntu-latest
          steps:
               - uses: actions/checkout@v4
               - uses: subosito/flutter-action@v2
                 with:
                      channel: stable
               - name: Detect goldens
                 id: detect
                 run: |
                      if ls examples/demo_game/goldens/*.png 2>/dev/null; then echo "present=true" >> $GITHUB_OUTPUT; else echo "present=false" >> $GITHUB_OUTPUT; fi
               - name: Run golden tests
                 if: steps.detect.outputs.present == 'true'
                 run: |
                      cd examples/demo_game
                      flutter test test/goldens
               - name: Ensure no uncommitted golden diffs
                 if: steps.detect.outputs.present == 'true'
                 run: |
                      if ! git diff --exit-code -- examples/demo_game/goldens; then
                        echo "Golden baselines changed. Did you forget to update and commit?" >&2
                        exit 1
                      fi
