name: Manifest Expander

on:
     push:
          branches: [main]
          paths-ignore:
               - 'packages/manifest.yaml'
     workflow_dispatch: {}

permissions:
     contents: write

jobs:
     expand:
          runs-on: ubuntu-latest
          steps:
               - uses: actions/checkout@v4
                 with:
                      fetch-depth: 0
               - uses: subosito/flutter-action@v2
                 with:
                      channel: stable
                      cache: true
               - name: Install dependencies
                 run: flutter pub get
               - name: Run manifest updater
                 run: dart run tools/update_manifest.dart
               - name: Commit manifest changes
                 run: |
                      set -e
                      if ! git diff --quiet -- packages/manifest.yaml; then
                        git config user.name 'ci-bot'
                        git config user.email 'ci-bot@users.noreply.github.com'
                        git add packages/manifest.yaml
                        git commit -m 'chore(manifest): add missing packages to manifest [skip ci]'
                        git push || true
                      else
                        echo 'Manifest already up-to-date.'
                      fi
