name: Metrics & Parity
on:
     push:
          branches:
               - main
               - chore/**
     pull_request:
          branches:
               - main

jobs:
     metrics:
          runs-on: ubuntu-latest
          steps:
               - name: Checkout
                 uses: actions/checkout@v4
               - name: Read Flutter pin
                 id: flutter_pin
                 run: |
                      if [ -f .github/flutter_version.txt ]; then echo "FLUTTER_VERSION=$(cat .github/flutter_version.txt)" >> $GITHUB_OUTPUT; else echo "FLUTTER_VERSION=stable" >> $GITHUB_OUTPUT; fi
               - name: Setup Flutter
                 uses: subosito/flutter-action@v2
                 with:
                      flutter-version: ${{ steps.flutter_pin.outputs.FLUTTER_VERSION }}
               - name: Flutter pub get
                 run: flutter pub get
               - name: Manifest completeness check
                 run: dart run tools/check_manifest.dart
               - name: Package status audit (non-blocking)
                 run: dart run tools/package_status_audit.dart
               - name: Run all package tests with coverage
                 run: bash tools/run_all_tests.sh
               - name: Quality gates
                 env:
                      COVERAGE_MIN: '25'
                 run: dart run tools/quality_gates.dart
               - name: Parity check
                 run: dart run tools/check_stub_parity.dart
               - name: Build symbol map (auto-update parity spec)
                 continue-on-error: true
                 run: |
                      dart run tools/build_symbol_map.dart \
                        --package in_app_purchase \
                        --out docs/metrics/in_app_purchase_symbols.json
               - name: Auto-update parity spec
                 continue-on-error: true
                 run: |
                      dart run tools/auto_update_parity_spec.dart \
                        --package in_app_purchase \
                        --symbols docs/metrics/in_app_purchase_symbols.json
               - name: Compute parity spec hash
                 id: spec
                 run: echo "hash=$(dart run tools/print_parity_spec_hash.dart)" >> $GITHUB_OUTPUT
               - name: Update metrics
                 env:
                      STUB_PARITY_OK: '1'
                      STUB_PARITY_SPEC_HASH: ${{ steps.spec.outputs.hash }}
                 run: dart run tools/update_metrics.dart
               - name: Route spec hash check (strict)
                 run: dart run tools/check_spec_hashes.dart --strict
               - name: Generate spec hashes (no-op if unchanged)
                 run: dart run tools/spec_hashes.dart --write
               - name: Commit metrics (if changed)
                 run: |
                      if [[ "$(git status --porcelain docs/METRICS.md docs/badges docs/SPEC_HASHES.md docs/metrics/spec_hashes.json)" != "" ]]; then
                        git config user.name "ci-bot"
                        git config user.email "ci-bot@example.com"
                        git add docs/METRICS.md docs/badges docs/SPEC_HASHES.md docs/metrics/spec_hashes.json || true
                        git commit -m "chore(metrics): update metrics & spec hashes [skip ci]" || echo "No changes"
                      fi
               - name: Commit parity spec (if changed)
                 run: |
                      if [[ "$(git status --porcelain tools/parity_spec/in_app_purchase.json docs/metrics/in_app_purchase_symbols.json)" != "" ]]; then
                        git config user.name "ci-bot"
                        git config user.email "ci-bot@example.com"
                        git add tools/parity_spec/in_app_purchase.json docs/metrics/in_app_purchase_symbols.json || true
                        git commit -m "chore(parity): auto-update parity spec & symbols [skip ci]" || echo "No changes"
                      fi
               - name: Upload parity artifacts
                 uses: actions/upload-artifact@v4
                 with:
                      name: parity-spec-and-symbols
                      path: |
                           docs/metrics/in_app_purchase_symbols.json
                           tools/parity_spec/in_app_purchase.json
               - name: Upload coverage artifact
                 uses: actions/upload-artifact@v4
                 with:
                      name: coverage-lcov
                      path: coverage/lcov.info
