name: Release Gates Mapping

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/RELEASE_GATES.md'
      - 'docs/metrics/release_gates.json'
      - 'README.md'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Dart Pub cache path
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Activate Melos
        run: dart pub global activate melos

      - name: Bootstrap workspace
        run: melos bootstrap

      - name: Generate release gates mapping
        run: dart run tools/generate_release_gates_table.dart

      - name: Commit mapping
        run: |
          set -e
          CHANGED=$(git status --porcelain docs/RELEASE_GATES.md docs/metrics/release_gates.json README.md | wc -l)
          if [ "$CHANGED" -gt 0 ]; then
            git config user.name 'ci-bot'
            git config user.email 'ci-bot@users.noreply.github.com'
            git add docs/RELEASE_GATES.md docs/metrics/release_gates.json README.md
            git commit -m 'chore(ci): update release gates mapping'
            git push || true
          else
            echo "No release gates changes to commit"
          fi