name: Generate Screenshots
on:
  repository_dispatch:
    types: [screenshots]
  workflow_dispatch:
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Android emulator (headless) & capture
        run: |
          echo "Stub: implement instrumentation tests to capture screenshots"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-screenshots
          path: assets/store/android/**
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fastlane snapshot (stub)
        run: |
          gem install fastlane
          echo "Stub: add Fastfile and Snapfile to drive iOS screenshots"
      - uses: actions/upload-artifact@v4
        with:
          name: ios-screenshots
          path: assets/store/ios/**
