name: Slash Commands
on:
  issue_comment:
    types: [created]
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          commands: |
            release-candidate
            epic
            submit-ios
            screenshots
            store
            promote
            hotfix
            rc
            project
          issue-type: both
