name: Submit iOS (TestFlight)
on:
  repository_dispatch:
    types: [submit-ios]
permissions:
  contents: read
jobs:
  submit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build IPA
        run: |
          flutter build ipa --release --no-codesign
      - name: Upload to TestFlight (Fastlane)
        run: |
          gem install fastlane
          fastlane pilot upload --ipa build/ios/ipa/*.ipa --skip_waiting_for_build_processing true
        env:
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APPSTORE_P8 }}
